// Generated by CoffeeScript 1.6.2
(function() {
  (function(W) {
    var bindEvent;
    bindEvent = function(elem, event, fn) {
      return elem.addEventListener(event, fn, false);
    };
    return W.plugin("pop-out", function(video, options) {
      var popOut, popped_out;
      if (options == null) {
        options = {};
      }
      popped_out = false;
      popOut = function() {
        var child_window;
        popped_out = true;
        return child_window = window.open();
      };
      return bindEvent(document.getElementById("pop-out-button"), "click", popOut);
    });
  })(Wistia);

}).call(this);
