// Generated by CoffeeScript 1.6.2
(function() {
  (function(W) {
    var bindEvent;
    bindEvent = function(elem, event, fn) {
      return elem.addEventListener(event, fn, false);
    };
    return W.plugin("custom-play-button", function(video, options) {
      var button_url, controls_visible, image, styleElem;
      if (options == null) {
        options = {};
      }
      button_url = options.buttonUrl || null;
      controls_visible = video.options.controlsVisibleOnLoad;
      console.log(controls_visible);
      image = new Image;
      image.onload = function() {
        var buttonPosition, logoHeight, logoWidth;
        image.className = "play-button";
        image.style.position = "absolute";
        buttonPosition = options.buttonPosition || "center";
        switch (buttonPosition) {
          case "center":
            video.grid.top_inside.appendChild(image);
            logoWidth = Wistia.util.elemWidth(image);
            logoHeight = Wistia.util.elemHeight(image);
            image.style.top = "" + ((wistiaEmbed.height() - logoHeight) / 2) + "px";
            return image.style.left = "" + ((wistiaEmbed.width() - logoWidth) / 2) + "px";
          case "top left":
            image.style.top = "20px";
            image.style.left = "20px";
            return video.grid.top_inside.appendChild(image);
          case "top right":
            image.style.top = "20px";
            image.style.right = "20px";
            return video.grid.top_inside.appendChild(image);
          case "bottom left":
            if (controls_visible = true) {
              image.style.bottom = "52px";
              image.style.left = "20px";
            } else {
              image.style.bottom = "20px";
              image.style.left = "20px";
            }
            return video.grid.bottom_inside.appendChild(image);
          case "bottom right":
            if (controls_visible = true) {
              image.style.bottom = "52px";
              image.style.right = "20px";
            } else {
              image.style.bottom = "20px";
              image.style.right = "20px";
            }
            return video.grid.bottom_inside.appendChild(image);
        }
      };
      image.src = button_url;
      bindEvent(image, "click", video.play());
      styleElem = W.util.addInlineCss(document.body, ".play-button {\nheight: 100px;\nopacity: 0.75;\n}\n\n.hidden {\ndisplay: none;\n}");
      wistiaEmbed.bind("play", function() {
        image.className = "hidden";
        return this.unbind;
      });
      if (video.options.endVideoBehavior === "reset") {
        return wistiaEmbed.bind("end", function() {
          image.className = "play-button";
          return this.unbind;
        });
      }
    });
  })(Wistia);

}).call(this);
